services:
  db:
    build:
      context: ./database     # Указываем Докеру смотреть в папку database
      dockerfile: Dockerfile  # Имя файла, который мы только что создали
    container_name: pawnwhop-db
    environment:
      POSTGRES_DB: pawnwhop
      POSTGRES_USER: pawnwhop_user
      POSTGRES_PASSWORD: pawnwhop_pass
    ports:
      - "5433:5432"
    volumes:
      - pawnwhop_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: "2"

volumes:
  pawnwhop_data: