spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5433/pawnwhop
spring.datasource.username=pawnwhop_user
spring.datasource.password=pawnwhop_pass
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
jwt.secret=8f3a9c7e5d1b4a6f9e2c8b7d6a5f4e3c2b1a9d8e7f6c5b4a3