# Базовые сетевые настройки (критично для Docker и IntelliJ)
listen_addresses = '*'
port = 5432

# Ресурсы памяти (ваши настройки)
shared_buffers = 1024MB
work_mem = 16MB
temp_buffers = 16MB

# Транзакции и файлы
max_prepared_transactions = 0
max_files_per_process = 1000

# Статистика
track_counts = on