spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5433/pawnwhop
spring.datasource.username=pawnwhop_user
spring.datasource.password=pawnwhop_pass
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false